version: '3'
services:
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_entity
      MYSQL_ROOT_HOST: '%'
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql    
    ports:
      - '3306:3306'